name = "Related-Shortcode"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme Component"
homepage = "Website of your theme"
tags = ["blog", "company"]
features = ["related", "theme-component", "shorcode"]
min_version = "0.59.1"


# If the theme has a single author
[author]
    name = "Damien Saunders"
    homepage = "Your website"

# If porting an existing theme
[original]
    author = "Name of original author"
    homepage = "His/Her website"
    repo = "Link to source code of original theme"
