name = "Content Shortcodes"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme Component"
homepage = "https://damien.co"
tags = ["blog", "company"]
features = ["related", "theme-component", "shorcode"]
min_version = "0.60"


# If the theme has a single author
[author]
    name = "Damien Saunders"
    homepage = "https://damien.co"

# If porting an existing theme
[original]
    author = "Name of original author"
    homepage = "His/Her website"
    repo = "Link to source code of original theme"
